version: '3.5'

services:
  gophermart:
    image: gophermart
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
      - MIGRATIONS_PATH=file://internal/app/storage/migrations/
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db:5432 -- gophermart'
  accrual:
    image: accrual
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
      - MIGRATIONS_PATH=file://internal/app/storage/migrations/
    ports:
      - "8081:8080"
    depends_on:
      - db
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db:5432 -- accrual'
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=praktikum
    ports:
      - '5432:5432'