version: '3.5'

services:

  gophermart:
    image: gophermart
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db_gophermart:5432/praktikum?sslmode=disable
      - MIGRATIONS_PATH=file:///usr/src/app/internal/gophermart/storage/migrations
      - RUN_ADDRESS=localhost:8080
    ports:
      - "8080:8080"
    depends_on:
      - db_gophermart
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db_gophermart:5432 -- gophermart'
  db_gophermart:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=praktikum
    ports:
      - '5432:5432'

  accrual:
    image: accrual
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    environment:
      - DATABASE_URI=postgres://postgres:postgres@db_accrual:5433/accrual?sslmode=disable
      - MIGRATIONS_PATH=file:///usr/src/app/internal/accrual/storage/migrations
    ports:
      - "8081:8080"
    depends_on:
      - db_accrual
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db_accrual:5432 -- accrual'

  db_accrual:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accrual
    ports:
      - '5433:5432'